// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBljXLPmSgD8pJOOJSrl1Eji1H2WiLWX2U',
    appId: '1:923125462848:web:f7fdc9be6fbc112df16ca5',
    messagingSenderId: '923125462848',
    projectId: 'fir-d2868',
    authDomain: 'fir-d2868.firebaseapp.com',
    databaseURL: 'https://fir-d2868-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'fir-d2868.appspot.com',
    measurementId: 'G-EN1LGSSX03',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDW5CLDVBTQwFgcieDlQJKQ3-6V-9qxsi0',
    appId: '1:923125462848:android:342b0fa8a7d2bd8cf16ca5',
    messagingSenderId: '923125462848',
    projectId: 'fir-d2868',
    databaseURL: 'https://fir-d2868-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'fir-d2868.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAGG4pcWDmx-iKSva4qcZ5y5mehhJIGzdY',
    appId: '1:923125462848:ios:0cd01e24bf08118bf16ca5',
    messagingSenderId: '923125462848',
    projectId: 'fir-d2868',
    databaseURL: 'https://fir-d2868-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'fir-d2868.appspot.com',
    androidClientId: '923125462848-qp5u99vdi3ihimlpe7v9ssqltkbp23d2.apps.googleusercontent.com',
    iosClientId: '923125462848-sfnd2f64qn0oepv2gcjqk1pigtq9fg9c.apps.googleusercontent.com',
    iosBundleId: 'com.example.lipReading',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAGG4pcWDmx-iKSva4qcZ5y5mehhJIGzdY',
    appId: '1:923125462848:ios:0cd01e24bf08118bf16ca5',
    messagingSenderId: '923125462848',
    projectId: 'fir-d2868',
    databaseURL: 'https://fir-d2868-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'fir-d2868.appspot.com',
    androidClientId: '923125462848-qp5u99vdi3ihimlpe7v9ssqltkbp23d2.apps.googleusercontent.com',
    iosClientId: '923125462848-sfnd2f64qn0oepv2gcjqk1pigtq9fg9c.apps.googleusercontent.com',
    iosBundleId: 'com.example.lipReading',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA6VQiNwUCfnnib2soZeiRljOh6ZNuRXE8',
    appId: '1:923125462848:web:8eb5e2c65531748ef16ca5',
    messagingSenderId: '923125462848',
    projectId: 'fir-d2868',
    authDomain: 'fir-d2868.firebaseapp.com',
    databaseURL: 'https://fir-d2868-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'fir-d2868.appspot.com',
    measurementId: 'G-Y3VC0LRBC5',
  );
}
